import { faBasketShopping, faUser } from '@fortawesome/free-solid-svg-icons';
import classNames from 'classnames/bind';

import styles from './Header.module.scss';
import {
    imgCate2,
    imgCate3,
    imgCate4,
    imgCate5,
    imgCate6,
    imgCate7,
    imgCate8,
    imgCate9,
    imgCate10,
    imgCate11,
    imgCate12,
    imgCate13,
} from '~/assets/images';

const cx = classNames.bind(styles);
const actions = [
    {
        icon: faBasketShopping,
        context: '(0) Giỏ hàng',
        link: '/cart',
    },
    {
        icon: faUser,
        context: 'Tài khoản',
        link: '/login',
    },
];
const navItems = [
    { name: 'Trang chủ', link: '/' },
    { name: 'Mã giảm giá', link: '/sale' },
    { name: 'Theo dõi đơn hàng', link: '/bill' },
];
const menuCate = [
    {
        name: 'Vi điều khiển - Nhúng',
        link: '/1',
        img: imgCate2,
        subMenu: [
            {
                name: 'Kit phát triển',
                link: '/2',
                subMenu: [
                    { name: '8051', link: '/3' },
                    { name: 'PIC', link: '/4' },
                    { name: 'ARM - STM', link: '/5' },
                    { name: 'Arduino', link: '/6' },
                    { name: 'Raspberry', link: '/7' },
                    { name: 'AVR', link: '/8' },
                    { name: 'Phụ kiện KIT', link: '/9' },
                    { name: 'NaNo - Pi', link: '/10' },
                ],
            },
            {
                name: 'Mạch nạp',
                link: '/11',
                subMenu: [
                    { name: 'Mạch nạp 8051', link: '/12' },
                    { name: 'Mạch nạp AVR', link: '/13' },
                    { name: 'Mạch nạp PIC', link: '/14' },
                    { name: 'Mạch nạp STM-ARM', link: '/15' },
                    { name: 'Mạch nạp MSP430', link: '/16' },
                    { name: 'Mạch nạp MSP430', link: '/17' },
                ],
            },
            {
                name: 'Vi điều khiển',
                link: '/',
                subMenu: [
                    { name: 'Vi điều khiển 8051', link: '/' },
                    { name: 'Vi điều khiển AVR', link: '/' },
                    { name: 'Vi điều khiển STM', link: '/' },
                    { name: 'PIC - DSPIC', link: '/' },
                    { name: 'Vi điều khiển MSP430', link: '/' },
                ],
            },
        ],
    },
    {
        name: 'Module ứng dụng',
        link: '/',
        img: imgCate3,
        subMenu: [
            { name: 'Module RF', link: '/' },
            { name: 'Module RFID', link: '/' },
            { name: 'Ethernet/Wifi', link: '/' },
            { name: 'Bluetooth', link: '/' },
            { name: 'Camera', link: '/' },
            { name: 'Sim-GMS/GPRS/GPS/3G', link: '/' },
            { name: 'Module động cơ', link: '/' },
            { name: 'Module SD', link: '/' },
            { name: 'Module VGA', link: '/' },
            { name: 'Module chuyển đổi', link: '/' },
            { name: 'Hồng ngoại/Ánh sáng', link: '/' },
            { name: 'Module relay', link: '/' },
            { name: 'Module nguồn', link: '/' },
            { name: 'Matrix phím', link: '/' },
            { name: 'Module driver', link: '/' },
            { name: 'Audio/MP3', link: '/' },
            { name: 'Thời gian/Tạo trễ', link: '/' },
            { name: 'Vân tay ( Finger-Print )', link: '/' },
            { name: 'Module AD', link: '/' },
            { name: 'Module DTMF', link: '/' },
            { name: 'Module led', link: '/' },
            { name: 'Khống chế nhiệt độ', link: '/' },
            { name: 'Đo dòng/Đo áp', link: '/' },
            { name: 'Máy in 3D', link: '/' },
            { name: 'Dao động/Phát xung', link: '/' },
            { name: 'Module tạo sương', link: '/' },
            { name: 'Module cảm biến', link: '/' },
        ],
    },
    {
        name: 'Cảm biến',
        link: '/',
        img: imgCate4,
        subMenu: [
            { name: 'Cảm biến nhiệt độ', link: '/' },
            { name: 'Cảm biến độ ẩm', link: '/' },
            { name: 'Cảm biến chuyển động', link: '/' },
            { name: 'Cảm biến ánh sáng', link: '/' },
            { name: 'Cảm biến khí', link: '/' },
            { name: 'Cảm biến siêu âm', link: '/' },
            { name: 'Cảm biến màu', link: '/' },
            { name: 'Cảm biến gia tốc,góc', link: '/' },
            { name: 'Cảm biến áp suất', link: '/' },
            { name: 'Cảm biến Từ', link: '/' },
            { name: 'Cảm biến nước', link: '/' },
            { name: 'Cảm biến khoảng cách', link: '/' },
            { name: 'Cảm biến âm thanh', link: '/' },
            { name: 'Cảm biến rung', link: '/' },
            { name: 'Load Cell', link: '/' },
            { name: 'Cảm biến dòng', link: '/' },
            { name: 'La bàn số', link: '/' },
            { name: 'Cảm biến nhịp tim', link: '/' },
            { name: 'Mở cửa/Báo động', link: '/' },
        ],
    },
    {
        name: 'Linh kiện điện tử',
        link: '/',
        img: imgCate5,
        subMenu: [
            {
                name: 'Linh kiện cơ bản',
                link: '/',
                subMenu: [
                    { name: 'Điện trở', link: '/' },
                    { name: 'Cuộn cảm', link: '/' },
                    { name: 'Tụ điện', link: '/' },
                ],
            },
            {
                name: 'Linh kiện bán dẫn',
                link: '/',
                subMenu: [
                    { name: 'Diode', link: '/' },
                    { name: 'Mosfet & Fets', link: '/' },
                    { name: 'Transistor', link: '/' },
                    { name: 'Triac-Thy-Diac', link: '/' },
                    { name: 'Opto-Photocouplers', link: '/' },
                ],
            },
            {
                name: 'Linh kiện thụ động',
                link: '/',
                subMenu: [
                    { name: 'Biến trở', link: '/' },
                    { name: 'Triết áp', link: '/' },
                    { name: 'Loa/Còi báo', link: '/' },
                    { name: 'Cầu chì', link: '/' },
                    { name: 'Thạch anh', link: '/' },
                    { name: 'Relay', link: '/' },
                    { name: 'Varistor/Tụ Chống Sét', link: '/' },
                    { name: 'Nút nhấn/Công tắc/SW', link: '/' },
                ],
            },
            {
                name: 'Led/Lcd/Text',
                link: '/',
                subMenu: [
                    { name: 'Led 7 thanh', link: '/' },
                    { name: 'Bóng đèn LED', link: '/' },
                    { name: 'LCD/Text', link: '/' },
                    { name: 'Led Matrix', link: '/' },
                    { name: 'Led Công Suất', link: '/' },
                ],
            },
        ],
    },
    {
        name: 'IC chức năng',
        link: '/',
        img: imgCate6,
        subMenu: [
            { name: 'IC nguồn', link: '/' },
            { name: 'Ic real time', link: '/' },
            { name: 'IC Opam', link: '/' },
            { name: 'IC giao tiếp', link: '/' },
            { name: 'IC CD', link: '/' },
            { name: 'IC công suất', link: '/' },
            { name: 'IC audio', link: '/' },
            { name: 'ADC/DAC', link: '/' },
            { name: 'IC driver', link: '/' },
            { name: '74HC/ 74LS/ IC số', link: '/' },
            { name: 'IC mã hóa/Giải mã', link: '/' },
            { name: 'IC cảm ứng', link: '/' },
            { name: 'IC can', link: '/' },
            { name: 'IC khác', link: '/' },
            { name: 'Đế IC', link: '/' },
        ],
    },
    {
        name: 'Thiết bị chế tạo',
        link: '/',
        img: imgCate7,
        subMenu: [
            {
                name: 'Robot mô hình',
                link: '/',
                subMenu: [
                    { name: 'Động cơ', link: '/' },
                    { name: 'máy bơm/Tạo khí', link: '/' },
                    { name: 'Máy bay mô hình', link: '/' },
                    { name: 'Mô hình/Xe robot', link: '/' },
                    { name: 'Phụ kiện', link: '/' },
                ],
            },
            {
                name: 'Thiết bị hàn',
                link: '/',
                subMenu: [
                    { name: 'Máy hàn', link: '/' },
                    { name: 'Thiếc hàn', link: '/' },
                    { name: 'Phụ kiện hàn', link: '/' },
                    { name: 'Máy Khò', link: '/' },
                ],
            },
            {
                name: 'Mạch in',
                link: '/',
                subMenu: [
                    { name: 'Phíp đồng', link: '/' },
                    { name: 'PCB/Board Test', link: '/' },
                    { name: 'Hóa chất', link: '/' },
                    { name: 'Dụng cụ phụ trợ', link: '/' },
                ],
            },
        ],
    },
    {
        name: 'Dụng cụ - phụ kiện',
        link: '/',
        img: imgCate8,
        subMenu: [
            {
                name: 'Dụng cụ cầm tay',
                link: '/',
                subMenu: [
                    { name: 'Kính lúp', link: '/' },
                    { name: 'Súng bắn keo', link: '/' },
                    { name: 'Máy khoan/Cắt/Mài', link: '/' },
                    { name: 'Phụ kiện máy khoan/Máy cắt', link: '/' },
                    { name: 'Kìm/Kẹp/Tua vít', link: '/' },
                ],
            },
            {
                name: 'Tản nhiệt/Cách điện',
                link: '/',
                subMenu: [
                    { name: 'Quạt tản nhiệt', link: '/' },
                    { name: 'Nhôm tản nhiệt', link: '/' },
                    { name: 'Keo/Mỡ tản nhiệt', link: '/' },
                    { name: 'Sò nóng lạnh và phụ kiện', link: '/' },
                ],
            },
            {
                name: 'Hộp các loại',
                link: '/',
                subMenu: [
                    { name: 'Hộp đựng 1 ngăn', link: '/' },
                    { name: 'Hộp đựng nhiều ngăn', link: '/' },
                ],
            },
            {
                name: 'Thiết bị đo/Kiểm tra',
                link: '/',
                subMenu: [
                    { name: 'Đồng hồ đo', link: '/' },
                    { name: 'Thước đo', link: '/' },
                    { name: 'Thiết Bị Đo', link: '/' },
                ],
            },
            {
                name: 'Tạo nguồn điện',
                link: '/',
                subMenu: [
                    { name: 'Nguồn adapter', link: '/' },
                    { name: 'Biến áp', link: '/' },
                    { name: 'Nguồn tổ ong/Nguồn xung', link: '/' },
                    { name: 'Pin, Ắc Quy', link: '/' },
                    { name: 'Mạch sạc pin, ắc quy', link: '/' },
                    { name: 'Box sạc dự phòng', link: '/' },
                    { name: 'Đế pin', link: '/' },
                    { name: 'Bộ chuyển đổi điện', link: '/' },
                    { name: 'Anten', link: '/' },
                ],
            },
            {
                name: 'Thiết bị gia dụng',
                link: '/',
                subMenu: [
                    { name: 'Thiết bị an toàn', link: '/' },
                    { name: 'Remote- Điều Khiển', link: '/' },
                    { name: 'Túi Đựng Dụng Cụ', link: '/' },
                ],
            },
        ],
    },
    {
        name: 'Connector',
        link: '/',
        img: imgCate9,
        subMenu: [
            {
                name: 'Dây kết nối',
                link: '/',
                subMenu: [
                    { name: 'Dây đồng/Dây điện', link: '/' },
                    { name: 'Dây cáp nối', link: '/' },
                    { name: 'Dây bus, Dây Buộc', link: '/' },
                    { name: 'Dây co nhiệt, chịu nhiệt', link: '/' },
                ],
            },
            {
                name: 'Cổng kết nối',
                link: '/',
                subMenu: [
                    { name: 'Terminal', link: '/' },
                    { name: 'Jack DC', link: '/' },
                    { name: 'Cổng USB', link: '/' },
                    { name: 'Header', link: '/' },
                    { name: 'Audio', link: '/' },
                    { name: 'Cổng DB-DP', link: '/' },
                    { name: 'IDE - IDC', link: '/' },
                    { name: 'Jumper', link: '/' },
                ],
            },
            {
                name: 'Phụ kiện',
                link: '/',
                subMenu: [
                    { name: 'Cọc đồng/Cọc nhựa', link: '/' },
                    { name: 'Kẹp cá sấu/ Móc', link: '/' },
                    { name: 'Socket', link: '/' },
                    { name: 'Ốc - Vít', link: '/' },
                ],
            },
        ],
    },
    {
        name: 'Sản phẩm combo',
        link: '/',
        img: imgCate10,
        subMenu: [
            { name: 'Combo máy hàn', link: '/' },
            { name: 'Combo máy khoan', link: '/' },
            { name: 'Sản phẩm DIY', link: '/' },
            { name: 'Combo khác', link: '/' },
        ],
    },
    {
        name: 'Nam châm đất hiếm',
        link: '/',
        img: imgCate11,
    },
    {
        name: 'Phụ kiện điện thoại',
        link: '/',
        img: imgCate12,
        subMenu: [
            { name: 'Pin Sạc', link: '/' },
            { name: 'Cáp Sạc', link: '/' },
            { name: 'Thẻ Nhớ', link: '/' },
            { name: 'Loa', link: '/' },
            { name: 'Giá Đỡ Điện Thoại', link: '/' },
            { name: 'Chuột/ Bàn Phím', link: '/' },
            { name: 'Ống Kinh Điện Thoai', link: '/' },
        ],
    },
    {
        name: 'Phụ kiện máy tính',
        link: '/',
        img: imgCate13,
        subMenu: [{ name: 'Dây Nguồn', link: '/' }],
    },
];

export { cx, actions, navItems, menuCate };
